#!/bin/bash
echo "Running Git hook to check commit message"

# validate commit message using regex
REGEX='^[A-Z].{6,50}$'

if ! [[ $1 =~ $REGEX ]]; then
  echo "Aborting commit, the commit message should be in sentence case and in imperative mood. Also make sure that the length is between 6-50 chars"
  exit 1
fi

echo "Commit message all good! :)"
