name: Push-to-EC2

# Trigger deployment on push and merge to master, dev branches
on:
  push:
    branches: [master, dev]
  pull_request_target:
    types: [closed]
    branches: [master, dev]

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ env.URL }}

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Apache Web Server on EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
